name: glados-auto-checkin

on:
  workflow_dispatch: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  0 10 * * * 
      # 
      # https://tool.lu/crontab/
      # https://datetime360.com/cn/utc-cst-china-time/
  #watch:
  #    types: started   

jobs:
  checkin:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
       # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: Checkin
      run: |
        python3 checkin.py 
      env: 
        SERVE: ${{ secrets.SERVE }}
        SCKEY: ${{ secrets.SCKEY }}
        COOKIE1: ${{ secrets.COOKIE1 }}
        COOKIE2: ${{ secrets.COOKIE2 }}
        COOKIE3: ${{ secrets.COOKIE3 }}
        COOKIE4: ${{ secrets.COOKIE4 }}
        COOKIE5: ${{ secrets.COOKIE5 }}

